# Generated by Django 3.0.4 on 2020-04-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0002_auto_20200404_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Offer_per',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
