# Generated by Django 3.0.4 on 2020-04-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0003_auto_20200404_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
